<?php
/**
 * @file
 * hr_assessments.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function hr_assessments_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "panelizer" && $api == "panelizer") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_node_info().
 */
function hr_assessments_node_info() {
  $items = array(
    'hr_assessment' => array(
      'name' => t('Assessment'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}
